kind: HTTPProxy
apiVersion: projectcontour.io/v1
metadata:
  namespace: application
  name: server
spec:
  routes:
    - services:
        - name: server
          port: 80
      loadBalancerPolicy:
        strategy: WeightedLeastRequest
      timeoutPolicy:
        idle: infinity
        response: infinity
  virtualhost:
    fqdn: api.testgoapp.in
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*" # allows any origin
      allowMethods:
        - GET
        - POST
        - OPTIONS
        - DELETE
      allowHeaders:
        - "*" # allows any origin
      exposeHeaders:
        - Content-Length
        - Content-Range
      maxAge: "10m" # preflight requests can be cached for 10 minutes.
    tls:
      secretName: server
