kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: application
  name: nodeserver
  annotations:
    git: https://github.com/ahmedwohlig/go-lang-application.git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeserver
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
        - name: nodeserver
          image: ahmedsurya/go-app:main-1a70e774ebbed706aae93484c0c288770d4c5508
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: server-config
          env:
            - name: NODE_ENV
              value: production
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
