kind: Service
apiVersion: v1
metadata:
  namespace: application
  name: server
spec:
  ports:
    - name: http1
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: server
  type: ClusterIP